### ISSUE TITLE
Show modifiers keys + mouse clics?

### ISSUE THREAD

**Issue by FrancoisSchnell** [Phaiax/Key-n-Stroke#17]
I wish to use PxKeystrokesForScreencasts to screencast creative softwares where there's a lot of 
(Shift or Ctrl or Alt) + left/middle/right mouse clicks (like Blender for example).

Currently testing on Win 8.1 version v 0.3.1 those modifiers keys don't appears in this case. 

Is there a settings I missed? If not would love to see it added to the todo list (nothing urgent).

Thanks for the great work!

**Comment by Phaiax** [comment]
Hey. Thanks.
No, its simply not possible.
I'm working on other projects right now, but i'll keep it in mind.
-phaiax

**Comment by Phaiax** [comment]
Released v1.0.0
Now there is an option to show the current active modifiers right next to the mouse while clicking/dragging
