### ISSUE TITLE
it doesn't work when a fullscreen game running.

### ISSUE THREAD

**Issue by Jokeylaw** [Phaiax/Key-n-Stroke#19]
Thanks for providing so amazing program,the application is beautiful,but when I run a fullscreen game like LOL,the form can't show above the game,I can solve this by setting the LOL to window model,but this game is fullscreen model by default,can someone give me some advices?that will be appreciated.Looking forward to the reply :-)

**Comment by Phaiax** [comment]
hmmm, don't know, but ill give it a try, maybe there is some unused z value

**Comment by Phaiax** [comment]
released v1.0.0

Now there is an option "Set in top periodically".
Hopefully that fixes it.
If not, I have no Idea 😅
