### ISSUE TITLE
Using Red and Blue Ripples on mouse clicks instead of icons

### ISSUE THREAD

**Issue by VarunJhajharia** [Phaiax/Key-n-Stroke#21]
Like many screen recording software use ripples to indicate mouse clicks, this feature could replace the current mouse icon display.
Use "Red" ripple to indicate Left Mouse Click and "Blue" ripple to indicate Right Mouse Click.
That would make the UI to take up less space and also look clean.

![caps2](https://cloud.githubusercontent.com/assets/25086172/22238829/6b04acf6-e1c8-11e6-938f-1749fdf4a0c2.gif)

Could also change the mouse highlighter color to indicate mouse clicks.

**Comment by Phaiax** [comment]
I'll think about it :D
Which program did you refer to?

**Comment by LeBaux** [comment]
I support this 👍 Maybe making it another option - sometimes the mouse click indicator is just not visible, mainly if your are clicking stuff in corners of your recording area.

**Comment by Phaiax** [comment]
released v1.0.0
Icons can now be customized. So that's not a full blown solution, but I hope some users create better looking icons 🛩️
