### ISSUE TITLE
click&drag not working

### ISSUE THREAD

**Issue by LazurURH** [Phaiax/Key-n-Stroke#26]
Was searching for a tool that could come handy at recording drawing tutorials. First time user for minutes, so maybe I'm just missing some options here. Works on win 10 64bit.
Click&drag, is a very often used combination in what I'm aiming for -creating video tutorials in inkscape- and somehow all it does is select a visual area of the capture tool instead of doing the right thing in inkscape. Hope it can be fixed easily.

**Comment by LazurURH** [comment]
Further testing. 
Clicking icons on screen does not work. 
Neither selecting objects by clicking.
Mouse wheel scrolling is ineffective with the capture tool. So scrolling the page slider by hover-over and scrolling doesn't work, also ctrl+mousewheel scroll doesn't zoom in. Somehow my key capturing stopped working too.

**Comment by Phaiax** [comment]
hopefully fixed with v1.0.0
