### ISSUE TITLE
"Indicate cursor position" negatively affects graphics tablet/mouse input

### ISSUE THREAD

**Issue by mukihyena** [Phaiax/Key-n-Stroke#27]
Indicate Cursor Position negatively affects graphics tablet/mouse input. Using a Cintiq 13 HD in Adobe Flash CS6 W10 64bit

see video:

https://youtu.be/tyhq531YFJU

**Comment by Phaiax** [comment]
fixed with v1.0.0

I tested it in FreshPaint with a touch sensitive pen and it worked. Hopefully that will fix it for you as well.
