### ISSUE TITLE
Passwords

### ISSUE THREAD

**Issue by hiiraa** [Phaiax/Key-n-Stroke#32]
Nice application. Thanks for making this.
One request from my side: Is it possible to make the app auto-disable while inserting passwords? OR at least make a shortcut key to enable-disable the app.
Thanks in advance.
Mahamud.

**Comment by ComputerCarl** [comment]
Fantastic utility!
I'd like to expand on what @hiiraa suggests and have a shortcut key which disables the text capture box but will still keep the mouse highlighting functionality. Also, in the settings, have the ability to disable the text box.

**Comment by Phaiax** [comment]
Now has an option to go to password mode (rightCtrl+F11 by default)
