### ISSUE TITLE
Invisible when recording screen with FFMPEG

### ISSUE THREAD

**Issue by lepatachou** [Phaiax/Key-n-Stroke#33]
Hi

I'm using https://sourceforge.net/projects/screencapturer/, based on FFMPEG

When I record the screen, the "black rectangle", witch is well in the bottom left of my main screen, doesn't appear in the video file. Too bad for a product usable for screencast.

**Comment by Phaiax** [comment]
Released v1.0.0

The App is now visible in screencapturer. (Except that screencapturer can't capture HighDpi screens)
