### ISSUE TITLE
Window on launch and cursor highlight position

### ISSUE THREAD

**Issue by narcolepticinsomniac** [Phaiax/Key-n-Stroke#37]
I was primarily looking for a cursor highlighter, and this program works pretty well. I really wish there was a way to to not show the window reminding users about the shortcut every time the program launches though. 

Also, the highlight doesn't initially locate the cursor position, so it remains in the upper left corner of the screen until the mouse moves.

**Comment by Phaiax** [comment]
Second point fixed.

First point made worse, now there is a even bigger welcome window 🛩️
