### ISSUE TITLE
Show mouse actions

### ISSUE THREAD

**Issue by PolyglotOpenstreetmap** [Phaiax/Key-n-Stroke#4]
I would like to replace QiPress with PxKeyStrokes. Is there a way to show mouse actions as well? Is it hard to detect double clicks? QiPress doesn't seem to do that.

**Comment by Phaiax** [comment]
I made this programm to suit my needs for coding screencasts and there was no need for any mouse interaction. Unfortunetally, I'm a linux user and do not use this program so frequently, that it pays of to implement this functionality. But this programm is open source and on github, and I will be happy to review and integrate any improvements done by anyone. So if you want to have a try implementing the mouse functionality, you're free to have a try. The IDE is free (Visual Studio Express (C#) or that new Code Studio (I don't know the exact name) from Microsoft.

**Comment by PolyglotOpenstreetmap** [comment]
Hi Phaiax,
I understand. I might implement this, but don't hold your breath. I'm rather busy with teaching people how to map for Openstreetmap.
Thanks for doing the hardest part: getting started with a free software solution for the problem.

Jo

**Comment by Phaiax** [comment]
Hey Openstreetmapper
I'm a a little bit bored today, so I decided to give it a try.
If you read this during the day, do you maybe have some time in the evening testing the new features and give feedback? I don't know how far I'm getting today, I'm just starting now, so there is a chance that it will get late or even become tomorrow .

**Comment by PolyglotOpenstreetmap** [comment]
I can definitely test it tonight or tomorrow.

Jo

**Comment by Phaiax** [comment]
Okay, there is a new release 0.2.0, please give it a try.
Commit references: 6d9b938 a9c1b13 ce50d9e 0415114 65ab9ca bb4f284

**Comment by Phaiax** [comment]
I just figured out that you maybe thought of another feature: Displaying the pressed buttons. But that will be only a minor change, the main win api stuff is already done.

What would be the most tutorial viewer friendly ui to display the mouse action?
 * symbols around the mouse itself (+ the viewer already looks at the mouse)
 * entries in the keystroke history window with symbols or text
 * colored indication of the circle around the mouse (- may cause bad lag)

I think ill go with the first choice. time is running :D

**Comment by PolyglotOpenstreetmap** [comment]
Hi Phaiax,
Sorry for not getting back to you more swiftly. Symbols that follow the mouse, would be really useful indeed. That way they don't clutter the keystroke window and as you say, that is where people are looking already anyway. Don't place them too near though. In this editor I'm using, the mouse pointer changes shape and a little icon is added to the bottom left to indicate in which mode it's operating.

Is it possible to detect double clicks? There is a mode (extrusion of rectangular shapes), where the user double clicks on the contour, to add a point. I think this is lost for the viewer with solution I'm using at the moment.

For logging it might be handy to have them in the keystroke window anyway. Bonus points if it can be made user configurable :-) Since I'm creating video and sometimes present for a public, the best place is where the action is, though.

Many thanks for implementing this!

Jo

**Comment by PolyglotOpenstreetmap** [comment]
I started testing the new code. Indeed, what I had in mind were the mouse buttons. Something odd about this editor (JOSM) is that you need to drag the right mouse button to pan the map. This seems counter intuitive at first, but you get used to it fairly quickly.
For somebody who is demonstrating text treatment systems, triple clicks, which select an entire line, instead of a single word, might also be interesting to show more prominently.

I'' m not entirely sure what the best way for visualizing it would be. The circle placed around the mouse could be divided in 2 halves. But how can it be made clear that it''s double or triple click?

Actually, I think it would be good if the translucent circle would only become visible when one of the buttons are clicked. (or half of it, depending on which button is clicked/held, not sure about the wheel, which can also act as a button) Oh, this is more complicated than I had imagined at first...

Jo

**Comment by PolyglotOpenstreetmap** [comment]
Hi Phaiax,

This is what a screencast now looks like:
http://www.twitch.tv/polyglot_openstreetmap/v/37371257

The dead keys mentioned in another ticket, are still buggy. (as you can see in the previous message).

Cheers,

Jo

**Comment by Phaiax** [comment]
https://www.reddit.com/r/picrequests/comments/42fu5f/icon_indicating_double_click/

**Comment by PolyglotOpenstreetmap** [comment]
Hi Phaiax, those icons look really nice. Especially the ones of Mystersinister. Easy to extend to triple click and very visual. I think it may make sense to divide the mouse wheel in half, or change its shape when it's scrolled up or down.
Jo

**Comment by Phaiax** [comment]
Commit references: 898ad90 Button indicator finished
651e323 Button indicator 3
a6aaeef Button indicator 2
67d3526 Button indicator 1

ive made some which are similar. maybe there could be a white band inbetween, but i also implemented a function, that freezes the icon for a short time after a doubleclick, so it is more clear that something happened.

Try it, and give feedback please

**Comment by PolyglotOpenstreetmap** [comment]
Hi, that's looking real good. At first I was thinking, where are the 'arcs' to indicate the double click, but the icon flashing also gets the message across, I think. I have another remark now. Not sure if you'd want me to Open another ticket for it. When pressing Shift+J. All you see is 'J'. In a way this makes sense, but in the case of this editor, it's important to show that Shift is part of the shortcut key. Maybe that could be a user setting too?

Oh, when it first starts, the mouse icon is there and it seems like the left mouse button is kept pressed. Then after actually pressing it, this goes away.

Great work! I'm sold on this one now :-) This is going to be very useful to show people how to map those places that are commercially not interesting enough to map.

Cheers,

Jo

**Comment by Phaiax** [comment]
Released v1.0.0

I'm creating another issue for the Shift+S thing
