### ISSUE TITLE
Info box at every start

### ISSUE THREAD

**Issue by www-jd8-de-Thomas-Koehler-PC-Training** [Phaiax/Key-n-Stroke#49]
Congratulations and thanks for this great and very useful tool! It would get a little more convenient, if the info box about shortcuts showing at every start could be reduced to the first 3-5 starts and not show up afterwards anymore. I hope I not myself nag you by my feedback.

**Comment by Phaiax** [comment]
It got even worse, there is now a welcome window 🛩️ 
Maybe I should add an option to hide that.

**Comment by Phaiax** [comment]
Implemented 09ddfa2ef45b73ba712786aa18b610ef95b87ced. Will be part of the next release.

Thanks for the suggestion!
