### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by sepsol** [Phaiax/Key-n-Stroke#50]
I really like your take on this utility. I just wish it had some more features when it comes to capturing keyboard input. If you don't mind I wanted to give some suggestions:

1.  It would be great if you could change the design of the keyboard tracker to something like [Carnac](https://github.com/Code52/carnac), even better yet, maybe you guys could collab with each other!

2. It would be awesome if you could change the current behavior of the keyboard tracker to something that more represents [QiPress](http://www.aalapshah.in/qipress). The current behavior tracks everything, I think it should only track the important keys as long as they're pressed. QiPress only shows a key while it's held down which in my opinion is at least a good option to have.

Your app is awesome, please don't let it die!

**Comment by Phaiax** [comment]
Last point (don't let it die) is fixed, but the other two points are not implemented.

For now implementation is not planned, but I keep this issue open as an inspiration

**Comment by Phaiax** [comment]
Added differentation between shortcut mode and text mode for the keystroke window (1cb7cf468aeb63a532cc6b4a59ca9f782664d418).

The program also alreay has the option to show modifier keys while clicking/dragging next to the mouse icon.

--> Close as "kinda implemented"

Thanks for the suggestions non the less.
