### ISSUE TITLE
Alignment Issues with Windows Display Scaling

### ISSUE THREAD

**Issue by ryanmillerca** [Phaiax/Key-n-Stroke#54]
Cursor is off by several hundred pixels on my computer, when using my 4K display at 175% scaling. Worth noting is that I have a second display at 1080p. Works fine if I don't use display scaling.

**Comment by stehlifn** [comment]
Any news here?

If you can get the windows scale this should be an easy fix. Please see attached gif for details.

![vZQkMLSxN9](https://user-images.githubusercontent.com/9286419/116553362-536ee900-a8fa-11eb-8a1e-daeacba1e31e.gif)

**Comment by riQQ** [comment]
This bug only affects Windows 8+.

**Comment by Phaiax** [comment]
I have a hole new version in development that's full multi screen multi dpi capable, but I find no time to finish it. Hopefully during the next weeks. 

Am 29. April 2021 14:51:38 MESZ schrieb Florian Stehling ***@***.***>:

**Comment by Phaiax** [comment]
Fixed with v1.0.0
