### ISSUE TITLE
Show only special keystrokes and other suggestions

### ISSUE THREAD

**Issue by embee0** [Phaiax/Key-n-Stroke#58]
What a wonderful tool! A few small and hopefully easily implementable suggestions:

1. add an option to only show "special" keystrokes, not the ones usually shown on the screen anyway. (Background: I want to record videos showing students good workflows with lots of handy keyboard shortcuts, but they shouldn't be distracted by showing the other stuff I type, eg code or text, twice)

2. I love that mouseclicks can be shown, but I find the mouse icon a bit... intrusive. On the other hand, I like the simple circle shown when "indicate cursor position" is checked. Could you make an option combining the two, i.e. just flashing the circle briefly on mouse clicks.

3. This is *really* minor: Laptops usually don't have RightCtrl, so maybe this isn't the ideal default key to use for "resize and move"

Among these issues, the first is the one that's really keeping me from using Key-n-Stroke in video recording. So if there's any chance...

Once again: Thanks a lot for your great work!

**Comment by Phaiax** [comment]
I'll keep that in mind

**Comment by Phaiax** [comment]
Implemented point 1 (only show special keystokes) via 5485c60819224aca19634343a6fd2fb5e9de2023 and 6d5d7b9c2dd3e842ede12599106f950f45687bae.

Point 2 implemented via 30d031ba9b61ca8d716efba502f2837e4ac4d43c and ccff03b2a24329a007389e27ef5f1d92798d6228.

Will be part of next release.

Thanks for the suggestions.
