### ISSUE TITLE
Key-n-Stroke doesn't run

### ISSUE THREAD

**Issue by AtwaterKent** [Phaiax/Key-n-Stroke#59]
Key-n-Stroke 1.0.0 doesn't run in this Windows 10 environment.  It will launch with the smart screen warning, I click "More Info" and "Execute Anyway" and then nothing. 
It doesn't appear in Task Manager. 
In Resource Monitor, its Status is "Suspended" and trying to End Process fails with the message "Access is denied." 
The only way to end the process is to restart.
I tried changing many Compatibility settings in Properties and running compatibility troubleshooter, running as Administrator. All failed.
Troubleshooter ultimately categorized it as "Incompatible Program - Fixed"

Reliability History had this info:
Source
KeyNStroke

Summary
Stopped working

Date
‎7/‎30/‎2021 5:24 PM

Status
Report sent

Problem signature
Problem Event Name:	CLR20r3
Problem Signature 01:	Key-n-Stroke.exe
Problem Signature 02:	1.0.0.0
Problem Signature 03:	eef6d148
Problem Signature 04:	mscorlib
Problem Signature 05:	4.8.4390.0
Problem Signature 06:	609c41da
Problem Signature 07:	339
Problem Signature 08:	10
Problem Signature 09:	System.ArgumentException
OS Version:	10.0.19043.2.0.0.256.48
Locale ID:	1033
Additional Information 1:	2beb
Additional Information 2:	2beba6fb4680d73a8c78ca7c24ccdb46
Additional Information 3:	6c14
Additional Information 4:	6c14eabbec4a762ea0aea5a3f0c42228

Any ideas/help would be appreciated.

**Comment by kmpm** [comment]
I have the same issue.
Release	Windows 10 Pro
Version	21H1
OS-Version	19043.1110

**Comment by Phaiax** [comment]
Hm. Maybe the NET Framework is missing. I thought .Net Framework 48 is installed by default on Windows 10.
Maybe you can find out which versions are installed on your machine: https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed

**Comment by kmpm** [comment]
I am not allowed to install 4.8 runtime since that or greater is already installed. But I still can't launch Key-n-Stroke.
```
dotnet --list-sdks
3.1.415 [C:\Program Files\dotnet\sdk]
5.0.104 [C:\Program Files\dotnet\sdk]
5.0.403 [C:\Program Files\dotnet\sdk]

dotnet --list-runtimes
Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
After installing the 4.8 developer pack from https://dotnet.microsoft.com/download/dotnet-framework/net48
(which shouldn't make any difference from before) I still can't launch. 
An old PxKeyStrokes.exe works.

**Comment by AtwaterKent** [comment]
Hello Phaiax,
Just wanted to say that while it took awhile for the [Key-n-Stroke doesn't run #59](https://github.com/Phaiax/Key-n-Stroke/issues/59#issue-957113869) issue to be addressed, it ultimately was. Not only is Key-n-Stroke  working but you've improved it, helping others to more easily follow complicated ideas and demonstrations. 
Thank you!
