### ISSUE TITLE
Default Keystroke History location covers tray

### ISSUE THREAD

**Issue by teknowledgist** [Phaiax/Key-n-Stroke#62]
Nice, simple program.  Thanks!

One, small issue:  The default location of the Keystroke History panel covers the clock and tray and makes the Key-n-Stroke icon practically invisible.

![image](https://user-images.githubusercontent.com/3977744/137000282-327d4bd4-a9e8-4ce0-99cb-1b16b037a9e5.png)

(It's there, but *really* hard to see.)

**Comment by ningjiazun** [comment]
Key-n-Stroke\KeyNStroke\App.xaml.cs

System.Windows.SystemParameters.PrimaryScreenHeight - mySettings.WindowSizeDefault.Height - 40);

**Comment by Phaiax** [comment]
Will be part of next release
