### ISSUE TITLE
Suggestion to add keyboard icons

### ISSUE THREAD

**Issue by ccasalicchio** [Phaiax/Key-n-Stroke#64]
Hi, there, I took an old version of your software and made some modifications to show actual keyboard letters, instead of normal text. If you find that interesting, can you maybe include that in your future versions? I can send you my solution if you'd like. :)

Here's a short video showing me typing this message.
http://splatdev.tech/issues/screencast_keyboard.gif
Best wishes

**Comment by Phaiax** [comment]
That looks nice, indeed. I'll keep that in Mind for possible future extensions.
Reusing the code will probably not work because I switched from WinForms to WPF.

**Comment by ccasalicchio** [comment]
If you ever get to that point, over already done all the work o creating an image for each keyboard key. I can send it to you if you'd like, and save you some time :)

Best wishes and great work! I really like your app

**Comment by ccasalicchio** [comment]
I can also become a contributor and work on adding that, if you agree to it.

**Comment by o-data** [comment]
I think you can just add a Pull Request and Phaiax will more likely to accept it.
