### ISSUE TITLE
Feature request: hide "Indicate cursor position" when mouse pointer disappears

### ISSUE THREAD

**Issue by ChrisJohnTaylor** [Phaiax/Key-n-Stroke#69]
Thanks again for a terrific program.

When I am watching a video on YouTube (for example), after a few seconds the mouse pointer disappears and only shows up again when you move your mouse. But the Key'n'Stroke circle highlighting the mouse pointer remains.

If it is possible, I think it would be good to have a checkbox in the "Settings" dialog along the lines of;

"Don't indicate cursor position if the mouse pointer disappears"

Cheers

**Comment by ChrisJohnTaylor** [comment]
Further to my last post, the mouse cursor disappears automatically when showing a PowerPoint deck as well. This is another place where having the "Indicate cursor position" remain on-screen is very distracting. It would nice, if possible, if it would only appear when the mouse pointer itself is showing.

Thanks!

Chris

**Comment by o-data** [comment]
Was about to create a thread about this too but luckily I notice this Issue before creating.

Yes, have the same issue so for the time being I just disable the 'circle' position until an update.

**Comment by Phaiax** [comment]
Impemented :) will be part of next release

e71f97a6997be5819b064483aee647a1fe93b3f1
8aa41c42564444de175d07def86b1de0c91d0526
8aa41c42564444de175d07def86b1de0c91d0526

**Comment by ChrisJohnTaylor** [comment]
Thanks!

**Comment by o-data** [comment]
Feature work great. I'm savvy enough to double click to Full Screen, but for the older or less 'mobile' user, they use the full screen bottom usually at bottom right of the player.

Not sure if this feature request will be popular request.

But can "Auto-Hide mouse after inactive" be added? I notice this situation occur on some of the user that I manage.

(Youtube) They click on the "Full Screen" button, screen go to full screen but for 1-2 second the mouse hover over the Time Seek bar, after a few more second the Time Seek bar will disappear, however the mouse is will there (hand mode). And it will stay there permanently as the mouse cursor still think you are selecting something.

Currently I'm using a free software call, "Auto Hide Mouse Cursor" and set it to about 5 second to auto hide if mouse is inactive to combat against this issue.

**Comment by ChrisJohnTaylor** [comment]
> Impemented :) will be part of next release
> 
> [e71f97a](https://github.com/Phaiax/Key-n-Stroke/commit/e71f97a6997be5819b064483aee647a1fe93b3f1) [8aa41c4](https://github.com/Phaiax/Key-n-Stroke/commit/8aa41c42564444de175d07def86b1de0c91d0526) [8aa41c4](https://github.com/Phaiax/Key-n-Stroke/commit/8aa41c42564444de175d07def86b1de0c91d0526)

Hi @Phaiax 

I had been watching on the main page for a new release and saw "Download Key-n-Stroke.exe 1.1.0 (most recent, **2021-02-08**)". So I thought it had not been updated yet. :-) 

I tested the new features and they are great! Thanks!
