### ISSUE TITLE
BUG: "Do not indicate mouse clicks" causes crash in certain circumstances

### ISSUE THREAD

**Issue by ev0net** [Phaiax/Key-n-Stroke#72]
Thanks for the tool. Just found it. Very useful in my video tutorial making.

To reproduce:
1. CHANGE RADIO: Mouse clicks > "Show icon on click" TO Mouse clicks >"Do not indicate mouse clicks" OR back and forth starting on: Mouse clicks >"Do not indicate mouse clicks"
2. CTRL (or other key) + MOUSE CLICK >>> program crash

**Comment by Phaiax** [comment]
Thanks a lot!. I could reproduce and fix that crash (535ba878fdf01daca862f961739b5c73ba063e83). Will be part of next release.

**Comment by ev0net** [comment]
Awesome! Thanks for fixing it. And I appreciate your app. I'm using it 
in creating singing, songwriting and recording instructional videos.
